/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StartupFunding } from "./StartupFunding";
export * as factories from "./factories";
export { StartupFunding__factory } from "./factories/StartupFunding__factory";
